{% set name = "symbrim" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/symbrim-{{ version }}.tar.gz
  sha256: 5aff45fd399cbdfe50bd6e731ac7529aef6ff73af2e9b091596fd6effaaec2f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - typing_extensions >=4.0.0,<5.0.0
    - sympy >=1.13.0,<2.0.0
    - numpy >=1.21.0,<3.0.0
    - importlib-metadata >=8.0.0,<9.0.0
  run_constrained:
    - symmeplot >=0.2.0,<0.3.0
    - bicycleparameters >=1.2.0,<2.0.0

test:
  imports:
    - symbrim
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://mechmotum.github.io/symbrim
  license: CC0-1.0
  license_file: LICENSE
  summary: A Modular and Extensible Open-Source Framework for Creating Symbolic Bicycle-Rider Models
  description: |
    SymBRiM is a Python package to model bicycle-riders symbolically. It offers a
    modular and extendable framework that empowers users to easily compose a custom
    bicycle-rider model. These models are build from a library of components, such as
    knife-edge wheels or toroidal-shaped wheels. The components serve as the building
    blocks of the system. Leveraging the open-source Python package SymPy, a computer
    algebra system, SymBRiM allows the usage of SymPy's bodies and joints interface to
    modify the model and other tools to manipulate the equations. The equations of
    motion for the system are derived using Kane's method, which can be further analysed
    and used in simulation and optimization tasks.
  doc_url: https://mechmotum.github.io/symbrim
  dev_url: https://github.com/mechmotum/symbrim

extra:
  recipe-maintainers:
    - tjstienstra
